name: trello_freestyler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  house-keeping:
    name: Keep it tight and stylie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: auto/test
    steps:
      - uses: actions/checkout@v2
      - run: auto/style-check
  build:
    needs: house-keeping
    name: Build + Publish Gem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          auto/publish
      - env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
